# Configuration for Enhanced Paper Updater
# ========================================

# Similarity thresholds (0.0 to 1.0)
arxiv_threshold: 0.7 # Higher threshold for arXiv matching
dblp_threshold: 0.6 # Slightly lower for published papers

# Rate limiting
delay_seconds: 1.5 # Delay between requests to avoid being blocked

# API limits
max_results: 20 # Maximum results to fetch per query

# Logging
log_level: INFO # DEBUG, INFO, WARNING, ERROR

# File handling
create_backups: true # Create .bak files before updating
backup_directory: backups # Directory for backups (optional)

# Data sources to use
sources:
  arxiv: true
  dblp: true
  crossref: false # Not implemented yet
  scholar: false # Not implemented yet
